language: node_js
node_js:
  - 12.6.0
script:
  - npm test
  - npm run build
deploy:
  edge: true
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  target_branch: master
  on:
    branch: develop